name: jupyter
prefix: /srv/jupyter
channels:
  - conda-forge
  - conda-forge/label/jupyterlab_beta
  - bioconda
dependencies:
  - python==3.11.*
  - jupyterlab==4.5.0b0
    # due to https://github.com/jupyterhub/jupyterhub/pull/4039
  - jupyterhub==5.*
  - jupyterhub-singleuser==5.*
  - pip
  - batchspawner==1.3.*
  - anywidget==0.9.*
  - numpy==1.25.*
  - pandas==1.5.3
  - matplotlib==3.9.*
  - seaborn==0.13.*
  - scikit-posthocs==0.11.4
  - matplotlib-venn==0.11.9
  - colormaps==0.4.2
  - upsetplot
  - statsmodels==0.14.*
  - kneed==0.8.5
  - numba
  - pyarrow
  - openpyxl
  - scipy==1.16.*
  - bioframe==0.7.2
  - pybbi==0.4.*
  - pybigtools==0.2.*
  - cooler=0.10.*
  - cooltools==0.7.1
  - natsort
  - tqdm
  - more-itertools
  - pip:
    - jupyterlab-materialdarker==0.7.1
    - pairtools==1.1.0
    - git+https://github.com/cchlanger/cooler_ontad.git
